server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VMate?useSSL=false&serverTimezone=UTC
    username: ${secret.dev-mysql-username}
    password: ${secret.dev-mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always